server:
  port: 8888   # 配置服务器默认端口

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-github-repo/config-repo  # 配置仓库的 Git 地址
          clone-on-start: true
