eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/  # 确保 Eureka 服务器地址正确
    register-with-eureka: true  # 是否注册到 Eureka
    fetch-registry: true  # 是否从 Eureka 拉取注册表
    #    enabled: false
    registry-fetch-interval-seconds: 30
    healthcheck:
      enabled: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id:  ${spring.application.name}:${server.port}
